name: 'Get ECR Repository'
description: 'Get the ECR repository to push to for a Github Actionrun'
inputs:
  app:
    description: 'The name of your service (testbox, onboarding, etc)'
    required: true
  layer:
    description: 'backend or frontend, or whatever else'
    required: false
  environment:
    description: 'The envrionment you want to deploy to'
    required: false
outputs:
  repository: # output will be available to future steps
    description: 'The repository you should push your Docker images into'
runs:
  using: 'node12'
  main: 'dist/index.js'
